# Generated by Django 4.1.5 on 2023-03-03 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0009_rename_cur_balance_balance_cur_summ_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="basketexpenses",
            name="store",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounting.store",
                verbose_name="Магазины",
            ),
            preserve_default=False,
        ),
    ]
