# Generated by Django 4.1.5 on 2023-03-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0010_basketexpenses_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="store_code",
            field=models.IntegerField(blank=True, null=True, verbose_name="Код МСИ"),
        ),
    ]
