# Generated by Django 4.1.5 on 2023-03-05 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0011_store_store_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basketexpenses",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounting.store",
                verbose_name="Магазины",
            ),
        ),
    ]
