# Generated by Django 4.1.5 on 2023-03-21 18:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0013_alter_basketexpenses_cost"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceIncome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_name",
                    models.CharField(max_length=255, verbose_name="Название источника"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BasketIncome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=datetime.datetime.utcnow,
                        verbose_name="Дата поступления",
                    ),
                ),
                (
                    "sum_income",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Сумма поступления",
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.card",
                        verbose_name="Карта",
                    ),
                ),
                (
                    "source_income",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.sourceincome",
                        verbose_name="Источник дохода",
                    ),
                ),
            ],
        ),
    ]
